OPTIONS(SKIP=1)
LOAD DATA 
INFILE  '/dbfiles/applcsf/cust/bin/bookdetails.txt'
INTO TABLE BOOKS_TEMP
REPLACE
FIELDS TERMINATED BY X'9'			
TRAILING NULLCOLS
( 
	AUTHOR_ID  "TRIM(:AUTHOR_ID)",    		      	
	BOOK_NAME "TRIM(:BOOK_NAME)",			
	ISBN "TRIM(:ISBN)", 	 		
	PAGES "TRIM(:PAGES)",          	 	
	COST "TRIM(:COST)",				
	PUBLISHED_DATE	"TO_DATE(:PUBLISHED_DATE,'DD/MM/YYYY')",		
	BOOK_TYPE "TRIM(:BOOK_TYPE)"

) 
