OPTIONS(SKIP=1)
LOAD DATA 
INFILE  '/dbfiles/applcsf/cust/bin/XXPATNI_BOOKS_UPLOAD_SRP.txt'
INTO TABLE cus.xxpatni_books_stage_srp
REPLACE
FIELDS TERMINATED BY X'9'			
TRAILING NULLCOLS
(
	BOOK_ID SEQUENCE(MAX,1), 
	AUTHOR_ID  "TRIM(:AUTHOR_ID)",    		      	
	BOOK_NAME "TRIM(:BOOK_NAME)",			
	ISBN_NUMBER "TRIM(:ISBN_NUMBER)", 	 		
	PAGES "TRIM(:PAGES)",          	 	
	COST "TRIM(:COST)",				
	PUBLISHING_DATE	"TO_DATE(:PUBLISHING_DATE,'DD/MM/YYYY')",		
	BOOK_TYPE "TRIM(:BOOK_TYPE)"

) 
